apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
  labels:
    app: fetch-metrics
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/metrics
